# Generated by Django 3.2.7 on 2021-10-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
