# Generated by Django 3.2.7 on 2021-10-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_art_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='sku',
        ),
    ]
