# Generated by Django 3.2.7 on 2021-10-08 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.CharField(max_length=1000000)),
                ('date_of_message', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_name', models.CharField(max_length=100)),
                ('chat_session', models.GenericIPAddressField()),
                ('reply_recieved', models.BooleanField(default=False)),
            ],
        ),
    ]
