# Generated by Django 3.2.7 on 2021-09-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210929_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat_session',
            field=models.GenericIPAddressField(),
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
