# Generated by Django 3.2.7 on 2021-10-25 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_of_message',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
