# Generated by Django 3.2.7 on 2021-10-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='status',
            field=models.CharField(max_length=1000000),
        ),
    ]
