# Generated by Django 3.2.7 on 2021-10-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_artist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_recieved',
            field=models.BooleanField(default=False),
        ),
    ]
